
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudInfo_v2._0_b._3
{

using System;
    using System.Collections.Generic;
    
public partial class Dnevnik_ConnectTable
{

    public int Id { get; set; }

    public Nullable<int> Id_Theme { get; set; }

    public Nullable<int> Id_Student { get; set; }

    public Nullable<int> Osenka { get; set; }

}

}
