
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudInfo_v2._0_b._3
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    public int Id { get; set; }

    public string S_Name { get; set; }

    public string S_Group { get; set; }

    public string S_Date { get; set; }

}

}
