

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudInfo_v2._0_b._3
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StudentDBEntities : DbContext
{
    public StudentDBEntities()
        : base("name=StudentDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Dnevnik_ConnectTable> Dnevnik_ConnectTable { get; set; }

    public virtual DbSet<ThemeDB> ThemeDBs { get; set; }

}

}

