
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudInfo_v2._0_b._3
{

using System;
    using System.Collections.Generic;
    
public partial class ThemeDB
{

    public int Id { get; set; }

    public string Data { get; set; }

    public string Theme { get; set; }

    public string Zadanie { get; set; }

}

}
